local options = {
  backup = false,
  clipboard = 'unnamedplus',
  completeopt = { 'menuone', 'noselect' },
  conceallevel = 0,
  fileencoding = 'utf-8',
  hlsearch = true,
  ignorecase = true,
  mouse = '',
  pumheight = 10,
  showmode = false,
  smartcase = true,
  smartindent = true,
  splitbelow = true,
  splitright = true,
  swapfile = false,
  timeoutlen = 300,
  undofile = true,
  updatetime = 250,
  writebackup = false,
  expandtab = true,
  shiftwidth = 4,
  tabstop = 4,
  cursorline = false,
  number = true,
  relativenumber = true,
  numberwidth = 4,
  signcolumn = 'yes',
  wrap = false,
  scrolloff = 10,
  sidescrolloff = 8,
  errorbells = false,
  hidden = true,
  autoread = true,
  incsearch = true,
  termguicolors = true,
  ls = 0,
  spell = true,
  breakindent = true,
  list = true,
  listchars = { tab = '» ', trail = '·', nbsp = '␣' },
  inccommand = 'split',
  laststatus = 0,
}

for k, v in pairs(options) do
  vim.opt[k] = v
end
