# Terminal settings
set -g default-terminal "tmux-256color"
set -s escape-time 0

# Prefix settings
unbind C-Space
set -g prefix C-Space
bind C-space send-prefix

# Reload config
bind-key r source-file ~/.tmux.conf

# General settings
setw -g mode-keys vi
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g mouse on
set-option -g history-limit 10000

# Window and pane creation
bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'

# Vim-style pane navigation in copy mode
bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

# Pane resizing
bind -n M-Left resize-pane -L 5
bind -n M-Right resize-pane -R 5
bind -n M-Up resize-pane -U 5
bind -n M-Down resize-pane -D 5

# Easy pane navigation without prefix
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# Additional key bindings
bind C-l send-keys 'C-l'
bind 'v' copy-mode

# Plugin management
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin "janoamaral/tokyo-night-tmux"

set -g @tokyo-night-tmux_theme night # storm | day | default to 'night'
set -g @tokyo-night-tmux_transparent 1  # 1 or 0

# Plugin settings
# set -g @continuum-restore 'on'

run '~/.tmux/plugins/tpm/tpm'
