# Terminal overrides
set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
set -s escape-time 0

# Keybinding settings
unbind C-Space
set -g prefix C-Space
bind C-space send-prefix
bind-key r source-file ~/.tmux.conf

# Base index settings
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# History settings
set -g mouse on
set-option -g history-limit 5000

# Window and pane creation settings
bind c new-window -c "#{pane_current_path}"

# Vim-specific bindings
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'

# Tmux version-specific bindings
tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'

if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"

if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

# Copy mode VI bindings
bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R

# Custom keybinding to clear screen
bind C-l send-keys 'C-l'

# Plugin manager settings
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Tokyo Night tmux theme settings
set -g @plugin "janoamaral/tokyo-night-tmux"
set -g @tokyo-night-tmux_theme night
set -g @tokyo-night-tmux_transparent 1
set -g @tokyo-night-tmux_bar_transparency 1
set -g @tokyo-night-tmux_window_id_style digital
set -g @tokyo-night-tmux_pane_id_style hsquare
set -g @tokyo-night-tmux_zoom_id_style dsquare
set -g @tokyo-night-tmux_terminal_icon 
set -g @tokyo-night-tmux_active_terminal_icon 
set -g @tokyo-night-tmux_window_tidy_icons 0
set -g @tokyo-night-tmux_show_datetime 0
set -g @tokyo-night-tmux_date_format YMD
set -g @tokyo-night-tmux_time_format 12H


# Optional features
# set -g @tokyo-night-tmux_show_music 1
# set -g @tokyo-night-tmux_show_netspeed 1
# set -g @tokyo-night-tmux_netspeed_iface "wlan0" # Detected via default route
# set -g @tokyo-night-tmux_netspeed_showip 1      # Display IPv4 address (default 0)
# set -g @tokyo-night-tmux_netspeed_refresh 1     # Update interval in seconds (default 1)

# Battery widget (optional)
# set -g @tokyo-night-tmux_show_battery_widget 1
# set -g @tokyo-night-tmux_battery_name "BAT1"  # some linux distros have 'BAT0'
# set -g @tokyo-night-tmux_battery_low_threshold 21 # default
# set -g @tokyo-night-tmux_show_hostname 1

# Run plugin manager
run '~/.tmux/plugins/tpm/tpm'
