set -ga terminal-overrides ",screen-256color*:Tc"
set-option -g default-terminal "screen-256color"
set -s escape-time 0

unbind C-Space
set -g prefix C-Space
bind C-space send-prefix
bind-key r source-file ~/.tmux.conf

setw -g mode-keys vi
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -g mouse on
set-option -g history-limit 30000

bind c new-window -c "#{pane_current_path}"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R

bind C-l send-keys 'C-l'
