preload = ~/Pictures/Wallpapers/wallhaven-0p5jkp.png
preload = ~/Pictures/Wallpapers/20250123_201242.jpg
preload = ~/Pictures/Wallpapers/301.jpg
preload = ~/Pictures/Wallpapers/299.jpg

preload = ~/Pictures/Wallpapers/284.jpg
preload = ~/Pictures/Wallpapers/279.jpg
preload = ~/Pictures/Wallpapers/277.jpg
preload = ~/Pictures/Wallpapers/276.jpg

wallpaper = ,~/Pictures/Wallpapers/284.jpg

splash = true
