preload = ~/Pictures/Wallpapers/wallhaven-gporqq.jpg
wallpaper = ,~/Pictures/Wallpapers/wallhaven-gporqq.jpg

splash = false
ipc = on
transition_fps = 60
transition_type = fade
transition_duration = 2
