$font = JetBrainsMono Nerd Font
$text = #c0caf5

general {
  disable_loading_bar = true
  hide_cursor = true
}

background {
    monitor =
    path = ~/Pictures/Wallpapers/279.jpg
    color = rgba(26, 27, 38, 1.0)
    blur_passes = 0
}

label {
  monitor =
  text = $TIME
  color = $text
  font_size = 90
  font_family = $font
  position = -30, 0
  halign = right
  valign = top
}

label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $text
  font_size = 25
  font_family = $font
  position = -30, -150
  halign = right
  valign = top
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0)
    outer_color = rgba(7aa2f7ee) rgba(bb9af7ee) 45deg
    check_color = rgba(9ece6aee) rgba(7aa2f7ee) 120deg
    fail_color = rgba(f7768eee) rgba(7aa2f7ee) 40deg
    font_color = rgb(192, 202, 245)
    fade_on_empty = false
    rounding = 15

    position = 0, -20
    halign = center
    valign = center
}

