$font = JetBrainsMono Nerd Font
$text = #c0caf5

general {
  disable_loading_bar = true
  hide_cursor = true
  grace = 2  # Allow grace period to unlock without password (seconds)
  no_fade_in = false  # Fade in when locking
}

background {
    monitor =
    path = ~/Pictures/Wallpapers/279.jpg
    color = rgba(26, 27, 38, 1.0)
    blur_passes = 3  # Add some blur to the background
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
}

label {
  monitor =
  text = $TIME
  color = $text
  font_size = 90
  font_family = $font
  position = -30, 0
  halign = right
  valign = top
  shadow_passes = 1  # Add subtle shadow to text
  shadow_size = 2
  shadow_color = 0x000000cc
}

label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $text
  font_size = 25
  font_family = $font
  position = -30, -150
  halign = right
  valign = top
  shadow_passes = 1
  shadow_size = 2
  shadow_color = 0x000000cc
}

input-field {
    monitor =
    size = 200, 50  # A bit larger input field
    outline_thickness = 3
    dots_size = 0.33 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.15 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    outer_color = rgba(7aa2f7ee) rgba(bb9af7ee) 45deg
    inner_color = rgba(0, 0, 0, 0.5)  # Slightly visible background
    font_color = rgb(192, 202, 245)
    fade_on_empty = true
    placeholder_text = <i>Password...</i>  # Italicized placeholder text
    hide_input = false
    rounding = 15
    check_color = rgba(9ece6aee) rgba(7aa2f7ee) 120deg
    fail_color = rgba(f7768eee) rgba(7aa2f7ee) 40deg
    position = 0, -20
    halign = center
    valign = center
}

