$font = JetBrainsMono Nerd Font

general {
  disable_loading_bar = true
  hide_cursor = true
}

background {
    monitor =
    path = ~/Pictures/Wallpapers/279.jpg
    color = rgba(25, 23, 36, 1.0)
    blur_passes = 0
}

label {
  monitor =
  text = $TIME
  color = $text
  font_size = 90
  font_family = $font
  position = -30, 0
  halign = right
  valign = top
}

label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $text
  font_size = 25
  font_family = $font
  position = -30, -150
  halign = right
  valign = top
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 3
    inner_color = rgba(0, 0, 0, 0.0)
    outer_color = rgba(eb6f92ee) rgba(c4a7e7ee) 45deg
    check_color = rgba(f6c177ee) rgba(eb6f92ee) 120deg
    fail_color = rgba(ebbcbaee) rgba(eb6f92ee) 40deg
    font_color = rgb(224, 222, 244)
    fade_on_empty = false
    rounding = 15

    position = 0, -20
    halign = center
    valign = center
}
