[colors.primary]
background = '#121212'  # Very dark gray background
foreground = '#b0b0b0'  # Light gray for foreground

[colors.normal]
black   = '#212121'  # Dark gray for black
red     = '#616161'  # Medium dark gray for red
green   = '#808080'  # Medium gray for green
yellow  = '#a0a0a0'  # Light gray for yellow
blue    = '#b0b0b0'  # Light gray for blue
magenta = '#b0b0b0'  # Light gray for magenta
cyan    = '#b0b0b0'  # Light gray for cyan
white   = '#b0b0b0'  # Light gray for white

[colors.bright]
black   = '#565f89'  # Darker gray for bright black
red     = '#616161'  # Medium dark gray for bright red
green   = '#808080'  # Medium gray for bright green
yellow  = '#a0a0a0'  # Light gray for bright yellow
blue    = '#b0b0b0'  # Light gray for bright blue
magenta = '#b0b0b0'  # Light gray for bright magenta
cyan    = '#b0b0b0'  # Light gray for bright cyan
white   = '#d0d0d0'  # Very light gray for bright white

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\\t"

[window]
padding = {x = 0, y = 0}
dynamic_padding = true
decorations = "None"
startup_mode = "Maximized"
opacity = 1
blur = true

[cursor]
style = {shape = "Block", blinking = "Off"}
unfocused_hollow = true

[mouse]
hide_when_typing = true

