blur-method = "dual_kawase"; # none for clean, dual_kawase
blur-strength = 3;

blur:
{
    background = true;
    background-frame = false;
    background-fixed = false;
};

opacity-rule = [
    "80:class_g = 'Alacritty'",
    "80:class_g = 'i3bar'",
];

backend = "glx";
fading = true;

fade-in-step = 0.1;
fade-out-step = 0.1;
vsync = true;
