# backend = "glx";
# vsync = true;

# opacity-rule = [
#     "80:class_g = 'Alacritty'",
#     "80:class_g = 'i3bar'",
# ];

# Shadow settings
# shadow = true;  # Enable shadows
# shadow-radius = 12;  # Shadow blur radius
# shadow-offset-x = -15;  # Horizontal offset of shadow
# shadow-offset-y = -15;  # Vertical offset of shadow
# shadow-opacity = 0.6;   # Opacity of shadows

# # Blur settings
# blur-background = true;
# blur-background-frame = false;
# blur-background-fixed = false;

# # Fading effect settings
# fading = false;          # Disable fading globally
# fade-in-step = 1;     # Speed of fade-in effect (ignored when fading = false)
# fade-out-step = 1;    # Speed of fade-out effect (ignored when fading = false)

# # Transparency for inactive windows
# inactive-opacity = 0.8;   # Set transparency for inactive windows
# active-opacity = 1.0;     # Full opacity for active windows

# # Blur effect settings (optional)
# blur-radius = 10;        # Radius of the blur

# # Disable fade on window opening/closing (affects workspace switching)
# no-fading-openclose = true;
