[window]
padding = { x = 0, y = 0 }
opacity = 0.9

[font]
normal = { family = "JetBrains Mono Nerd Font", style = "Regular" }
bold = { family = "JetBrains Mono Nerd Font", style = "Bold" }
size = 14.0

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[general]
import = ["~/.cache/wal/colors-alacritty.toml"]
