[general]
import = [ "~/.cache/wal/colors-alacritty.toml" ]

[window]
  padding = {x = 0, y = 0}
  dynamic_padding = true
  decorations = "None"
  startup_mode = "Maximized"
  opacity = 0.8
  blur = true
  dimensions = { columns = 120, lines = 30 }
  dynamic_title = true
  option_as_alt = "Both"

[font]
  normal = { family = "MesloLGLDZ Nerd Font Mono", style = "Regular" }
  bold   = { family = "MesloLGLDZ Nerd Font Mono", style = "Bold" }
  italic = { family = "MesloLGLDZ Nerd Font Mono", style = "Italic" }
  size = 12
  offset = { x = 0, y = 1 }
  glyph_offset = { x = 0, y = 0 }
  builtin_box_drawing = true

[scrolling]
  history = 10000
  multiplier = 3

[cursor]
  style = {shape = "Block", blinking = "Off"}
  unfocused_hollow = true

[mouse]
  hide_when_typing = true

[selection]
  save_to_clipboard = true
  semantic_escape_chars = ",│`|:\"' ()[]{}<>\\t"
