[window]
  padding = {x = 0, y = 0}
  dynamic_padding = true
  decorations = "None"
  startup_mode = "Maximized"
  opacity = 0.8
  blur = true

[font]
  normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
  bold   = { family = "JetBrainsMono Nerd Font", style = "Bold" }
  italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
  size = 10

[scrolling]
  history = 10000
  multiplier = 3

[cursor]
  style = {shape = "Block", blinking = "Off"}
  unfocused_hollow = true

[mouse]
  hide_when_typing = true

[selection]
  save_to_clipboard = true
  semantic_escape_chars = ",│`|:\"' ()[]{}<>\\t"

[colors.primary]
foreground = "#e0def4"
background = "#191724"
dim_foreground = "#908caa"
bright_foreground = "#e0def4"

[colors.cursor]
text = "#e0def4"
cursor = "#eb6f92"

[colors.vi_mode_cursor]
text = "#e0def4"
cursor = "#eb6f92"

[colors.search.matches]
foreground = "#908caa"
background = "#26233a"

[colors.search.focused_match]
foreground = "#191724"
background = "#ebbcba"

[colors.hints.start]
foreground = "#908caa"
background = "#1f1d2e"

[colors.hints.end]
foreground = "#6e6a86"
background = "#1f1d2e"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#e0def4"
background = "#1f1d2e"

[colors.selection]
text = "#e0def4"
background = "#403d52"

[colors.normal]
black   = "#26233a"
red     = "#eb6f92"
green   = "#31748f"
yellow  = "#f6c177"
blue    = "#9ccfd8"
magenta = "#c4a7e7"
cyan    = "#ebbcba"
white   = "#e0def4"

[colors.bright]
black   = "#6e6a86"
red     = "#eb6f92"
green   = "#31748f"
yellow  = "#f6c177"
blue    = "#9ccfd8"
magenta = "#c4a7e7"
cyan    = "#ebbcba"
white   = "#e0def4"

[colors.dim]
black   = "#1a1723"
red     = "#d65a7a"
green   = "#27627f"
yellow  = "#d9aa67"
blue    = "#8ab9c9"
magenta = "#af97d7"
cyan    = "#d4a4ac"
white   = "#c0bfd4"
