;==========================================================
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;   For more info, visit: https://github.com/polybar/polybar
;==========================================================

[colors]
background = #aa1A1B26
background-alt = #24283b
foreground = #C0CAF5
primary = #7aa2f7
secondary = #9ece6a
alert = #f7768e
disabled = #3b4261

[bar/example]
width = 100%
height = 18pt
background = ${colors.background}
foreground = ${colors.foreground}
line-size = 1pt
padding-left = 0
padding-right = 1
module-margin = 1
separator = /
separator-foreground = ${colors.disabled}
font-0 = FiraCode Nerd Font;3
modules-left = xworkspaces
modules-right = spotify wlan filesystem memory cpu temperature backlight pulseaudio battery date systray

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true
bottom = true

[module/systray]
type = internal/tray
format-margin = 0pt
tray-spacing = 8pt

[module/backlight]
type = internal/backlight
card = intel_backlight
use-actual-brightness = true
poll-interval = 0
format = <label>
format-prefix = "󰃝 "
format-prefix-foreground = ${colors.primary}
label = %percentage%%

[module/battery]
type = internal/battery
full-at = 99
low-at = 5
battery = BAT1
adapter = ACAD
poll-interval = 5
time-format = %H:%M
format-charging = <animation-charging> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>
label-charging = %percentage%%
label-discharging = %percentage%%
label-full =  %percentage%%
label-low =  %percentage%%
ramp-capacity-0 =  
ramp-capacity-1 =  
ramp-capacity-2 =  
ramp-capacity-3 =  
ramp-capacity-4 =  
bar-capacity-width = 10
animation-charging-0 =  
animation-charging-1 =  
animation-charging-2 =  
animation-charging-3 =  
animation-charging-4 =  
animation-charging-framerate = 750
animation-discharging-0 =  
animation-discharging-1 =  
animation-discharging-2 =  
animation-discharging-3 =  
animation-discharging-4 =  
animation-discharging-framerate = 500
animation-low-0 = !
animation-low-1 = 
animation-low-framerate = 200

[module/xworkspaces]
type = internal/xworkspaces
label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline = ${colors.primary}
label-active-padding = 1
label-occupied = %name%
label-occupied-padding = 1
label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1
label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:60:...%

[module/filesystem]
type = internal/fs
interval = 25
mount-0 = /
label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix = " "
format-volume-prefix-foreground = ${colors.primary}
label-volume = %percentage%%
format-volume = <label-volume>
format-muted = <label-muted>
label-muted =  MUTED
label-muted-foreground = ${colors.disabled}
click-right = pavucontrol

[module/temperature]
type = internal/temperature
interval = 0.5
thermal-zone = 0
zone-type = x86_pkg_temp
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon2/temp1_input
base-temperature = 20
warn-temperature = 80
format = <ramp> <label>
format-warn = <ramp> <label-warn>
label = %temperature-c%
label-warn = %temperature-c%
label-warn-foreground = #f00
ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = ${colors.primary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage_used:2%%

[module/cpu]
type = internal/cpu
interval = 1
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%
warn-percentage = 95
format = <label>

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

[module/wlan]
inherit = network-base
interface-type = wireless
; label-connected = %{F#9ECE6A} %downspeed%%{F-} %{F#C0CAF5} %upspeed%%{F-} %{F#F0C674}%ifname%%{F-} %{F#FFFFFF}%local_ip% 
label-connected = %{F#9ECE6A}%downspeed%%{F-}

[module/eth]
inherit = network-base
interface-type = wired
; label-connected = %{F#9ECE6A} %downspeed%%{F-} %{F#C0CAF5} %upspeed%%{F-} %{F#F0C674}%ifname%%{F-} %{F#FFFFFF}%local_ip% 
label-connected = %{F#9ECE6A}%downspeed%%{F-}

[module/date]
type = internal/date
interval = 1
date = %Y-%m-%d %I:%M %p
date-alt = %Y-%m-%d %I:%M:%S %p
label = %date%
label-foreground = ${colors.primary}

[settings]
screenchange-reload = true
pseudo-transparency = false

[module/spotify]
type = custom/script
tail = true
interval = 1
; prefix symbol is shown before the text
format-prefix = "󰎇 "
format = <label>
exec = ~/.config/polybar/scripts/scroll_spotify_status.sh
click-left = playerctl --player=spotify play-pause 
click-right = playerctl --player=spotify next 
click-middle = playerctl --player=spotify previous 
