# Global properties
separator=true
separator_block_width=15

[mediaplayer]
command=./scripts/mediaplayer
instance=spotify
interval=5
signal=10

[Youtube]
full_text=
website=https://youtube.com
command=xdg-open "$website"
color=#FF4500  # Brighter Gruvbox red

[GPT]
full_text=
website=https://chatgpt.com/
command=xdg-open "$website"
color=#00C853  # Brighter Gruvbox green

[Reddit]
full_text=
website=https://www.reddit.com/
command=xdg-open "$website"
color=#FF4500  # Brighter Gruvbox red

# [docker]
# command=./scripts/docker
# color=#40E0D0  # Brighter Gruvbox cyan
# interval=10
# LABEL=🐳

[dunst]
command=./scripts/dunst
markup=pango
interval=once
format=json

# [bandwidth]
# command=./scripts/bandwidth
# interval=persist
# markup=pango

[iface]
command=./scripts/iface
LABEL=
IFACE=wlan0
ADDRESS_FAMILY=inet6?
color=#32CD32  # Brighter Gruvbox light green
interval=10
display_wifi_name=1

[battery]
command=./scripts/battery
markup=pango
interval=30
color=#FFD700  # Brighter Gruvbox yellow

# [optimus-manager]
# command=./scripts/optimus-manager
# interval=30

[temperature]
command=./scripts/temperature
label= 
interval=10
color=#FFA500  # Brighter Gruvbox orange

[memory]
command=./scripts/memory
label= 
interval=30
color=#4682B4  # Brighter Gruvbox blue

[cpu_usage]
command=./scripts/cpu_usage
interval=10
LABEL= 
color=#8A2BE2  # Brighter Gruvbox purple

# [disk]
# command=./scripts/disk
# LABEL= 
# ALERT_LOW=10
# interval=30
# color=#FF1493  # Brighter Gruvbox pink

[calendar]
command=./scripts/calendar
interval=30
LABEL= 
DATEFMT=+%Y-%m-%d %I:%M:%S %p
color=#ffffff

