separator=true
separator_block_width=15

[mediaplayer]
command=./scripts/mediaplayer
instance=spotify
interval=5
signal=10
color=#7aa2f7


# [bandwidth]
# command=./scripts/bandwidth
# interval=persist
# markup=pango
# color=#7dcfff

[battery]
command=./scripts/battery
markup=pango
interval=30
color=#e0af68

[cpu_usage]
command=./scripts/cpu_usage
interval=2
color=#bb9af7

[temperature]
command=./scripts/temperature
interval=10
color=#ff9e64

[memory]
command=./scripts/memory
interval=30
color=#9ece6a

[calendar]
command=./scripts/calendar
interval=30
DATEFMT=+%Y-%m-%d %I:%M:%S %p
color=#7aa2f7

[dunst]
command=./scripts/dunst
markup=pango
interval=once
format=json
color=#c0caf5
