separator=true
separator_block_width=15

[mediaplayer]
command=./scripts/mediaplayer
instance=spotify
interval=5
signal=10
color=#b0b0b0  ; Light gray color for the mediaplayer

[battery]
command=./scripts/battery
interval=30
LABEL=⚡
color=#b0b0b0  ; Light gray color for the battery

[cpu_usage]
command=./scripts/cpu_usage
interval=2
color=#a0a0a0  ; Medium light gray for CPU usage

[memory]
command=./scripts/memory
interval=30
color=#b0b0b0  ; Light gray color for memory usage

[calendar]
command=./scripts/calendar
interval=60
DATEFMT=+%a %b %d, %Y %I:%M %p
color=#b0b0b0  ; Light gray color for the calendar

[dunst]
command=./scripts/dunst
markup=pango
interval=once
format=json
color=#b0b0b0  ; Light gray for notifications

